server:
  port: 3000

spring:
  banner:
    location: classpath:config/banner-name.txt
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB
  datasource:
    url: jdbc:h2:~/h2-db/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

upload:
  path:
    name: uploads
